[tool.poetry]
name = "chatchat_openai_server"
version = "0.3.0.20240708"
description = "chatchat_openai_server"
authors = ["chatchat"]
packages = [
    {include = "chatchat_openai_server"}
]



[tool.poetry.dependencies]
python = ">=3.8.1,<3.12,!=3.9.7"

